from math import radians

from EngineArguments import DefaultArguments as args
from EngineArguments.DefaultArguments import base_arguments_o
from EngineComponents.Abstract.Material import NarloyZ

le5a_kwargs = base_arguments_o | {
    'thrust': 121.3e3,
    'combustion_chamber_pressure': 40e5,
    'expansion_ratio': 130,
    'mass_mixture_ratio': 5,
    'fuel_name': 'LH2_NASA',
    'burn_time': 609,
    'exit_pressure_forced': None,
    'expansion_ratio_end_cooling': 30
}
le5_kwargs = {'fuel_name': 'LH2_NASA',
              'thrust': 103e3,
              'combustion_chamber_pressure': 3.65e6,
              'expansion_ratio': 140,
              'mass_mixture_ratio': 5.5,
              'area_ratio_chamber_throat': 3.11,
              'chamber_characteristic_length': 0.84,
              'turbine_maximum_temperature': 837,
              'gg_pressure': 2.63e6,
              'fuel_pump_outlet_pressure': 6.04,
              'oxidizer_pump_outlet_pressure': 5.19,
              'fuel_pump_efficiency': 61.2e-2,
              'oxidizer_pump_efficiency': 65.3e-2,
              'burn_time': 0,
              'turbine_pressure_ratio': 0,
              'turbine_efficiency': 0,
              }

# Data from Kakuma 2000, Aoki 2001
le5b_kwargs = args.base_arguments_o | {
    'thrust': 137e3,
    'fuel_name': 'LH2_NASA',
    'mass_mixture_ratio': 5.0,
    'expansion_ratio': 110,
    'exit_pressure_forced': None,
    'ambient_pressure': 0,
    'burn_time': 534,
    'expansion_ratio_end_cooling': 6,  # Visual approximation
    'area_ratio_chamber_throat': 3.11,  # From McHugh1995
    'combustion_chamber_pressure': 3.62e6,
    'turbine_maximum_temperature': 409,
    'oxidizer_turbine_pressure_ratio': 2.172,
    'fuel_turbine_pressure_ratio': 5.125,
    'fuel_initial_temperature': 21,
    'oxidizer_initial_temperature': 90,
    # Assumed (from SE21D)
    'divergent_throat_half_angle': radians(15),
    'specific_impulse_quality_factor': .99,
    'oxidizer_turbine_efficiency': .40,
    'fuel_turbine_efficiency': .40,
    'shaft_mechanical_efficiency': .95,
    'oxidizer_exhaust_exit_pressure_forced': .04e6,
    'oxidizer_secondary_specific_impulse_quality_factor': .98,
    'exhaust_material': NarloyZ,
    'fuel_pump_efficiency': .75,
    'oxidizer_pump_efficiency': .8,
    'fuel_initial_pressure': 4e5,
    'oxidizer_initial_pressure': 2e5,
    # 'fuel_initial_pressure': 3e5,
    # 'oxidizer_initial_pressure': 6e5,
    'turbopump_specific_power': 13.5E3,
    # 'fuel_pump_outlet_pressure_forced': 6.86e6,
    # 'oxidizer_pump_outlet_pressure_forced': 5.3e6,
}

se_21d_kwargs = args.base_arguments_o | {
    'thrust': 1947.03e3,
    'combustion_chamber_pressure': 6.649e6,
    'fuel_initial_temperature': 21,
    'oxidizer_initial_temperature': 90,
    'expansion_ratio': 12.52,
    'mass_mixture_ratio': 5.5,
    'fuel_name': 'LH2_NASA',
    'burn_time': 100,
    'expansion_ratio_end_cooling': 5,
    'chamber_characteristic_length': 4.0,
    'fuel_pump_efficiency': .7,
    'secondary_fuel_pump_efficiency': .75,
    'oxidizer_pump_efficiency': .76,
    'fuel_initial_pressure': .3e6,
    'oxidizer_initial_pressure': .5e6,
    'turbine_maximum_temperature': 506.452,
    'turbopump_specific_power': 13.5E3,
    'area_ratio_chamber_throat': (.985 / 2) ** 2 / .286 ** 2,
    'ambient_pressure': 101325,
    'divergent_throat_half_angle': radians(15),
    'specific_impulse_quality_factor': .99,
    'oxidizer_turbine_efficiency': .45,
    'fuel_turbine_efficiency': .45,
    'shaft_mechanical_efficiency': .99,
    'oxidizer_exhaust_exit_pressure_forced': .04e6,
    'fuel_exhaust_exit_pressure_forced': .04e6,
    'oxidizer_turbine_outlet_pressure_forced': .3e6,
    'fuel_turbine_outlet_pressure_forced': .3e6,
    'oxidizer_secondary_specific_impulse_quality_factor': .98,
    'fuel_secondary_specific_impulse_quality_factor': .98,
    'exhaust_material': NarloyZ,
}
se_21d_vac_kwargs = se_21d_kwargs | {'thrust': 2196.682e3, 'ambient_pressure': 0}
mira_kwargs = base_arguments_o | {
    'thrust': 100e3,
    'combustion_chamber_pressure': 48e5,
    'expansion_ratio': 125,
    'mass_mixture_ratio': 3.9,
    'fuel_name': 'CH4',
    # 'fuel_density': 423.9,
    'fuel_initial_temperature': 115,
    'oxidizer_initial_temperature': 90,
    'burn_time': 100,
    'exit_pressure_forced': None,
    'maximum_wall_temperature': 800,
    'distance_from_throat_start_cooling': None,
    'distance_from_throat_end_cooling': .4,
    'chamber_characteristic_length': 1.3,
    'fuel_pump_efficiency': .7,
    'oxidizer_pump_efficiency': .7,
    'fuel_initial_pressure': 3e5,
    'oxidizer_initial_pressure': 3e5,
    'fuel_pump_pressure_factor': 1.6,
    'oxidizer_pump_pressure_factor': 1.3,
    'turbine_pressure_ratio': 14.478260869565217391304347826087,
    'turbine_gas_specific_heat_capacity': None,
    'turbine_gas_heat_capacity_ratio': None,
    'turbopump_specific_power': 13.5E3,
    'turbine_efficiency': .6,
    'area_ratio_chamber_throat': (.985 / 2) ** 2 / .286 ** 2,
    'divergent_throat_half_angle': radians(25),
    'exhaust_expansion_ratio': 20

}
vinci_kwargs = base_arguments_o | {
    'fuel_initial_temperature': 20.25,
    'thrust': 180e3,
    'combustion_chamber_pressure': 60.8e5,
    'expansion_ratio': 240,
    'mass_mixture_ratio': 5.8,
    'area_ratio_chamber_throat': None,
    'chamber_characteristic_length': None,
    'fuel_name': 'LH2_NASA',
    'burn_time': 720,
    'exit_pressure_forced': None,
    'expansion_ratio_end_cooling': None,
    'maximum_wall_temperature': 850,
}
